fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: uv run black docling_parse tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: uv run isort docling_parse tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: uv run autoflake docling_parse tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: uv run mypy docling_parse tests
        pass_filenames: false
        language: system
        files: '\.py$'
#  - repo: local
#    hooks:
#      - id: pytest
#        name: Pytest
#        entry: uv run pytest tests/
#        pass_filenames: false
#        language: system
#        files: '\.py$'	
  - repo: local
    hooks:
      - id: system
        name: uv check
        entry: uv lock --check
        pass_filenames: false
        language: system
