on:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build_wheels:
    name: Build wheel for py${{ matrix.python-version }} ${{ matrix.os.platform_id }}
    runs-on: ${{ matrix.os.name }}

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      # list of github vm: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      fail-fast: false
      matrix:
        python-version: ["3.10"]

        os:
          - name: "windows-latest"
            platform: "windows"
            platform_id: "win_amd64"

# if: matrix.os.name == 'ubuntu-latest' || matrix.os.name == 'macos-latest'
# if: matrix.os.name == 'windows-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true


      - name: Load cached venv
        id: cached-pip-wheels
        uses: actions/cache@v4
        with:
          # Set the path based on the operating system
          path: ${{ runner.os == 'Windows' && 'C:\\Users\\runneradmin\\AppData\\Local\\pypa\\cibuildwheel\\Cache' || '~/.cache' }}
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      # - name: Install dependencies
      #   # if: matrix.os.name == 'windows-latest'
      #   run: C:\Users\runneradmin\.local\bin\poetry install --no-interaction --no-root --only=build
      #   shell: pwsh

      - name: Convert Python version to cpXYZ
        # if: matrix.os.name == 'windows-latest'
        shell: pwsh
        run: |
          $version = "${{ matrix.python-version }}"
          $cp_version = "cp$($version -replace '\.', '')"
          Add-Content -Path $env:GITHUB_ENV -Value "python_cp_version=$cp_version"

      - name: Build wheels
        # if: matrix.os.name == 'windows-latest'
        env:
          CIBW_PLATFORM: windows
          CIBW_BUILD_VERBOSITY: 3
          # CIBW_BUILD: ${{ env.python_cp_version }}
          CIBW_ARCHS: AMD64
          CIBW_PROJECT_REQUIRES_PYTHON: "~=${{ matrix.python-version }}.0"
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; 
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install zlib
          C:\Users\runneradmin\.local\bin\poetry install --no-interaction --no-root --only=build
          C:\Users\runneradmin\.local\bin\poetry run python --version
          C:\Users\runneradmin\.local\bin\poetry run python -m cibuildwheel --output-dir .\wheelhouse

      - name: Publish wheels (dry run)
        # if: matrix.os.name == 'windows-latest'
        shell: pwsh
        run: |
          ls -l ./dist
          C:\Users\runneradmin\.local\bin\poetry publish --dry-run --no-interaction -vvv

