on:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build_wheels:
    name: Build wheel for py${{ matrix.python-version }} ${{ matrix.os.platform_id }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

        os:
          # - name: "windows-latest"
          - name: "windows-2019"
            platform: "windows"
            platform_id: "win_amd64"
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Convert Python version to cpXYZ
        # if: matrix.os.name == 'windows-latest'
        shell: pwsh
        run: |
          # adds poetry path
          echo "C:\Users\runneradmin\.local\bin" >> $env:GITHUB_PATH
          # creates python version env
          $version = "${{ matrix.python-version }}"
          $cp_version = "cp$($version -replace '\.', '')"
          Add-Content -Path $env:GITHUB_ENV -Value "python_cp_version=$cp_version"

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-zlib

      - name: Build with MSYS2
        run: |
          # Use the MSYS2 shell to run commands
          C:/msys64/usr/bin/bash -c "
          echo Setting PKG_CONFIG_PATH...
          export PKG_CONFIG_PATH=/mingw64/lib/pkgconfig

          echo Testing if pkg-config can find zlib...
          pkg-config --cflags --libs zlib
      - name: Build wheels
        # if: matrix.os.name == 'windows-latest'
        env:
          CIBW_PLATFORM: windows
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ARCHS: AMD64
          CIBW_PROJECT_REQUIRES_PYTHON: "~=${{ matrix.python-version }}.0"
          CMAKE_PREFIX_PATH: "C:/msys64/mingw64"
          PKG_CONFIG_PATH: "C:/msys64/mingw64/lib/pkgconfig"
          BUILD_THREADS: 2
        shell: cmd
        run: |
          if exist C:\Strawberry rmdir /s /q C:\Strawberry
          echo Testing if pkg-config can find zlib...
          pkg-config --cflags --libs zlib
          echo Building wheels...
          poetry install --no-interaction --no-root --only=build
          poetry run python -m cibuildwheel --output-dir .\wheelhouse

      - name: Publish wheels (dry run)
        # if: matrix.os.name == 'windows-latest'
        shell: cmd
        run: |
          dir .\dist
          poetry publish --dry-run --no-interaction -vvv
