on:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build_wheels:
    name: Build wheel for py${{ matrix.python-version }} ${{ matrix.os.platform_id }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

        os:
          - name: "windows-2019"
            platform: "windows"
            platform_id: "win_amd64"
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-nasm

      - name: Convert Python version to cpXYZ and set paths
        shell: pwsh
        run: |
          $version = "${{ matrix.python-version }}"
          $cp_version = "cp$($version -replace '\.', '')"
          Add-Content -Path $env:GITHUB_ENV -Value "python_cp_version=$cp_version"

      - name: Build wheels
        env:
          CIBW_PLATFORM: windows
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ARCHS: AMD64
          CIBW_PROJECT_REQUIRES_PYTHON: "~=${{ matrix.python-version }}.0"
          PKG_CONFIG_PATH: "C:/msys64/mingw64/lib/pkgconfig"
          CMAKE_PREFIX_PATH: "C:/msys64/mingw64"
          CMAKE_LIBRARY_PATH: "C:/msys64/mingw64/lib" 
          CMAKE_INCLUDE_PATH: "C:/msys64/mingw64/include"
          CMAKE_GENERATOR: "MSYS Makefiles"
          ASM_NASM: "C:/msys64/mingw64/bin/nasm.exe"
          BUILD_THREADS: 1
        shell: cmd
        run: |
          if exist "C:\Strawberry\" rmdir /s /q "C:\Strawberry\"
          set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin
          set PATH=%PATH%;C:\Users\runneradmin\.local\bin
          poetry install --no-interaction --no-root --only=build
          poetry run python -m cibuildwheel --output-dir ./wheelhouse
